# Tested on Vcenter 6.
---
- hosts: DEV
  gather_facts: false
  
  tasks:

  # Create a VM from a template.
  - name: create the VM
    vmware_guest:
      # Validate_certs must be false in case the Vcenter use a self-signed certificate.
      validate_certs: false
      hostname: '{{ vsphere_host }}'
      username: '{{ vsphere_user }}'
      password: '{{ vsphere_password }}'
      datacenter: '{{ vsphere_datacenter }}'
      resource_pool: "POC_Auto_RP"
      folder: "CBGI/POC_Auto"
      name: 'ADOP1'
      guest_id: Ubuntu64Guest
      template: POC_Auto_Ubuntu_16.04.3LTS
