---
- hosts: dev
  gather_facts: false
  connection: local

  vars_prompt:
    - name: "vsphere_host"
      prompt: "vSphere Host"
      private: no
    - name: "vsphere_user"
      prompt: "vSphere User"
      private: no
    - name: "vsphere_password"
      prompt: "vSphere Password"
    - name: "vsphere_template"
      prompt: "vSphere Template"
      private: no
    - name: "vsphere_folder"
      prompt: "vSphere Folder"
      private: no
    - name: "vsphere_resourcepool"
      prompt: "vSphere Resource Pool"
      private: no
    - name: "vsphere_datacenter"
      prompt: "vSphere Datacenter"
      private: no
      
  tasks:
  # get date
  - set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"

  # Create a VM from a template
  - name: create the VM
    vmware_guest:
      validate_certs: false
      hostname: '{{ vsphere_host }}'
      username: '{{ vsphere_user }}'
      password: '{{ vsphere_password }}'
      datacenter: '{{ vsphere_datacenter }}'
      resource_pool: '{{ vsphere_resourcepool }}'
      folder: "{{ vsphere_folder}}"
      name: 'test_ansible_2'
      state: poweredon
      guest_id: Ubuntu64Guest
      annotation: '{{ creationdate }}'
      template: '{{ vsphere_template }}'
