---
- hosts: adop
  gather_facts: false

  tasks:

  - name: Lunch ADOP installation, STEP 3-2 Executing installation, installing ADOP... it may take a while
    become: true
    shell: |
       export INITIAL_ADMIN_USER="administrator"
       ./adop compose init >> /tmp/adop_test_3_log.txt
    args:
      chdir: /root/adop-docker-compose/

  - name: Copy installation log from remote to local in /tmp
    become: true
    fetch:
      src: /tmp/adop_test_3_log.txt
      dest: /tmp/adop_test_3_log.txt
